repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        stages: [commit, manual]
        files: '.*\.(py|html|css|js|md|yml|yaml)$'
    -   id: end-of-file-fixer
        stages: [commit, manual]
        files: '.*\.(py|html|css|js|md|yml|yaml)$'
    -   id: check-yaml
        stages: [commit, manual]
    -   id: check-added-large-files
        stages: [commit, manual]

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        stages: [commit, manual]
        args: ["--line-length=120"]
        files: '.*\.py$'

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        stages: [commit, manual]
        args: ["--max-line-length=120"]
        additional_dependencies: [flake8-django]
        files: '.*\.py$'

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        stages: [commit, manual]
        args: ["--profile=black", "--line-length=120"]
        files: '.*\.py$'

-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
    -   id: djlint-django
        stages: [commit, manual]
        args: ["--reformat", "--max-line-length=120"]
        files: '.*\.(html|djhtml)$'
