name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python3.10.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
        cache: 'pip'

    - name: Run pre-commit hooks
      run: |
        pip install pre-commit black isort flake8 djlint
        pre-commit install
        pre-commit run --all-files

    - name: Run tests
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # Install main requirements with verbosity
        pip install -v -r requirements.txt
        python manage.py test

    # - name: Run tests with coverage
    #   run: |
    #     pytest -v --cov=web --cov-report=xml

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: true

    # - name: Check for security vulnerabilities
    #   run: |
    #     pip install safety
    #     safety check
